import AntdClientWrapper from "@/components/AntdClientWrapper";
import ThemeProvider from "@/components/themeProvider/ThemeProvider";
import ServerNav from "@/components/ServerNav"; // 使用服务端导航组件
import "./globals.css";

// 如需定义元数据，可在这里添加（服务端组件支持）
// export const metadata: Metadata = {
//   title: 'My App',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 服务端组件仅负责输出根结构，客户端逻辑交给AntdClientWrapper
  return (
    <html lang="en">
      <body className="antialiased">
        {/* 引入客户端组件处理Antd和动态逻辑，服务端仅渲染静态容器 */}
        <AntdClientWrapper>
          <ThemeProvider>
            {/* 使用服务端导航组件（内部包含客户端动态逻辑） */}
            <ServerNav /> 
            {children}
          </ThemeProvider>
        </AntdClientWrapper>
      </body>
    </html>
  );
}
